- hosts: all 
  become: True
  tasks:
    - name: install a webserver on ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu'
    - name: start the service
      service:
         name: apache2
         state: started
      when: ansible_distribution == 'Ubuntu'
    - name: Deploy static website
      copy:
        src: index.php
        dest: /var/www/html/